#!/bin/bash

#set -xv

PATH=$PATH:.local/bin
CMD=dell_p4317q_serial_control_program.py
MOD=$(basename ${0##*_})
SHP=50

OPT=$#

# Layout:
# 
# 4x4:
#
#  3 | 4
# ---+---
#  2 | 1
#
# SxS:
#
#  2 | 1

IN0=${1:-vga}
IN1=${2:-dp}
IN2=${3:-mdp}
IN3=${4:-hdmi1}
IN4=${5:-hdmi2}

declare -a INPUT=("${IN0}" "${IN1}" "${IN2}" "${IN3}" "${IN4}")

power_cycle() {
    if [[ "${IN0}" =~ np ]];then
        return
    fi
    read -p "Are you sure to power-cycling ?"
    sleep .5
    #${CMD} get powerstate | grep -q  ON || ${CMD} set powerstate 1
    ${CMD} set powerstate 0
    sleep 6
    ${CMD} set powerstate 1
}

init_sub() {
    if [[ "${IN0}" =~ help ]];then
        echo "Default settings for input:"
        echo -e "\t" vga ${INPUT[1]} ${INPUT[2]} ${INPUT[3]} ${INPUT[4]}
        exit
    elif [ ${MOD} == 4x4 -a ${OPT} -ge 1 -a ${IN0} != 'np' ];then
        echo "Cannot set input"
        exit 1
    fi
    sleep .5
    INDEX=0
    for IN in ${INPUT[1]} ${INPUT[2]} ${INPUT[3]} ${INPUT[4]};do
        ${CMD} set pxpsubinput ${INDEX} ${IN}
        sleep 1
        echo ${INDEX}: ${IN}
        INDEX=$((${INDEX}+1))
    done 
}

init_mode_and_sharp() {
    sleep .5
    ${CMD} set pxpmode ${MOD}
    sleep .5
    ${CMD} set sharpness ${SHP}
}

init_sub
init_mode_and_sharp
power_cycle
