#!/bin/bash

#set -xv

PATH=$PATH:~/.local/bin:$(dirname ${0})
CMD=dell_p4317q_serial_control_program.py
MOD=$(basename ${0##*_})
SHP=50

OPT=$#

# Layout:
# 
# 4x4:
#
#  3 | 4
# ---+---
#  2 | 1
#
# SxS:
#
#  2 | 1

IN0=${1:-vga}
IN1=${2:-dp}
IN2=${3:-mdp}
IN3=${4:-hdmi1}
IN4=${5:-hdmi2}

declare -a INPUT=("${IN0}" "${IN1}" "${IN2}" "${IN3}" "${IN4}")

power_cycle() {
    if [[ "${IN0}" =~ np ]];then
        return
    fi
    read -t 4 -p "Are you sure to power-cycling ? [N/y] " NY
    NY=${NY:-N}
    case $yn in
        [Yy]*)
            sleep .5
            ${CMD} set powerstate 0
            sleep 6
            ${CMD} set powerstate 1
            ;;
        [Nn]*)
            ;;
        *)
            ;;
    esac
    echo
}

init_mode_and_sharp() {
    if [ ${MOD} == pip ];then
        local MOD=4k
    fi
    sleep .5
    ${CMD} set pxpmode ${MOD}
    sleep .5
    ${CMD} set sharpness ${SHP}
}

init_sub() {
    if [[ "${IN0}" =~ help ]];then
        echo "Default settings for input:"
        echo -e "\t" vga ${INPUT[1]} ${INPUT[2]} ${INPUT[3]} ${INPUT[4]}
        exit
    fi
    if [ ${MOD} == 4x4 ];then
        INPUT[0]=vga
    fi
    if [ ${MOD} == 4k ];then
        ${CMD} set videoinput ${INPUT[1]}
    elif [ ${MOD} == pip ];then
        ${CMD} set videoinput ${INPUT[1]}
        sleep 2
        #${CMD} set pxpmode bigPip
        ${CMD} set pxpmode smallPip
        sleep 6
        #${CMD} set pxplocation bottomRight
        ${CMD} set pxplocation bottomLeft
        sleep .5
        ${CMD} set pxpsubinput 1 ${INPUT[2]}
    else
        sleep .5
        INDEX=0
        for IN in ${INPUT[1]} ${INPUT[2]} ${INPUT[3]} ${INPUT[4]};do
            ${CMD} set pxpsubinput ${INDEX} ${IN}
            sleep 1
            echo ${INDEX}: ${IN}
            INDEX=$((${INDEX}+1))
        done 
    fi
}

init_mode_and_sharp
init_sub
power_cycle
